services:

  mysql:
    image: mysql:8

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: waste_db

    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:

    build: ./backend

    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: waste_db

    depends_on:
      - mysql

  frontend:
    build: ./frontend

  nginx:

    build: ./nginx

    ports:
      - "80:80"

    depends_on:
      - frontend
      - backend